### ISSUE TITLE
EDT support?

### ISSUE THREAD

**Issue by fschuindt** [am32-firmware/AM32#19]
Is EDT on DShot600 supported? Moreover, is there an official documentation page? Or list of features?

Thank you!

**Comment by fschuindt** [comment]
It seems it does, as [found on the Discord server](https://discord.com/channels/1029170737342316605/1029170737342316608/1215411619950239855).

**Comment by howels** [comment]
> It seems it does, as [found on the Discord server](https://discord.com/channels/1029170737342316605/1029170737342316608/1215411619950239855).

EDT and dsho600 is supported, please refer to the betaflight docs
https://betaflight.com/docs/wiki/getting-started/hardware/esc-firmware#am32

**Comment by shrinibas7** [comment]
Does the motor phase back-EMF signal go through a comparator circuit before reaching the MCU, or is it connected directly with just a resistor
