### ISSUE TITLE
STM32G031 support

### ISSUE THREAD

**Issue by zyura** [am32-firmware/AM32#20]
I successfully built and ran AM32 on my custom board using the STM32F051 microcontroller, and it's working fine (thanks for your work!).

Would it be feasible to run AM32 on the STM32G031G8U6? These microcontrollers come in a smaller 4x4 package and are more cost-effective compared to the F051.

While there's a target for the F031, there isn't one for the G031. If you believe it's possible to adapt AM32 for the G031, I'm willing to modify my board accordingly, conduct testing, and submit the necessary patch.

Regards.

**Comment by zyura** [comment]
There's "[Migration of applications from STM32F0 Series to STM32G0 Series](https://www.st.com/resource/en/application_note/an5145-migration-of-applications-from-stm32f0-series-to-stm32g0-series--stmicroelectronics.pdf)" app note discussing the subject.

So basically my question is about possible nuances that would make it hard or impossible to run AM32 on G031.

**Comment by zyura** [comment]
When using its options to use PA9 instead of PA11 and PA10 instead of PA12 the pinout becomes compatible with HARDWARE_GROUP_F0_A.

![STM32G031G8U6](https://github.com/am32-firmware/AM32/assets/1634532/03f8d731-f6e1-4dc1-9635-0ea3d7e7c478)

**Comment by AlkaMotors** [comment]
G031 has no comparators. G071is compatible and supported.  The G051 will work too.

**Comment by zyura** [comment]
You're right, didn't notice this. Thanks.
