### ISSUE TITLE
Is there any link to bootloader?

### ISSUE THREAD

**Issue by lida2003** [am32-firmware/AM32#62]
I didn't see any OTA code, is it in bootloader?

So is there any link to bootloader?

--- EDIT

It seems the bootloader is somewhere else, which needs to be move to new repo https://github.com/am32-firmware/AM32/pull/54???

**Comment by lida2003** [comment]
Quite confused, there are quite a lot of links to bootloader.

https://github.com/AlkaMotors/AM32_Bootloader_F051
https://github.com/AlkaMotors/F051_Bootloader_Updater
https://github.com/AlkaMotors/g071Bootloader

https://github.com/AlkaMotors/AT32F421_AM32_Bootloader
https://github.com/AlkaMotors/AT32F415_AM32_Bootloader

**Comment by tridge** [comment]
@lida2003 
we now have a common bootloader
https://github.com/am32-firmware/AM32-bootloader

**Comment by lida2003** [comment]
Thanks @tridge
