### ISSUE TITLE
DSHOT 2400 Support ?

### ISSUE THREAD

**Issue by devararendy** [am32-firmware/AM32#63]
Hi, im very interested to this project. from what i see in the description, AM32 currently support DSHOT 600.
Is there any milestone for supporting DSHOT 2400 ?

I hope i can help to contribute in this project

**Comment by freasy** [comment]
Current prerelease 2.16rc3 supports dshot2400

**Comment by devararendy** [comment]
Woww thank you so much, glad to hear that 🥳
